# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.3.0

collections:
  developers-en:
    lang: en
    output: true
    permalink: /developers/:path/
  developers-zh_CN:
    lang: zh_CN
    output: true
    permalink: /zh_CN/developers/:path/

defaults:
  -
    scope:
      path: ""
      type: developers-en
    values:
      layout: developers
  -
    scope:
      path: ""
      type: developers-zh_CN
    values:
      layout: developers

pages:


t:
  en:
    language: English
    language_title: Language
    home:
      title: Home
      url: '/'
    about:
      title: About
      url: '/about/'
  zh_CN:
    language: 简体中文
    language_title: 语言
    home:
      title: 主页
      url: '/zh_CN/'
    about:
      title: 关于
      url: '/zh_CN/about/'
