# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Namati Documentation
description:         ''
url:                 https://angusmcleod.github.io/namati-wiki
baseurl:             '/namati-wiki'
resources_path:      '/public/resources'

sass:
  style: :compressed

markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jekyll-redirect-from

# Custom vars
version:             1.3.0

exclude: ['/tools']

collections:
  en:
    output: true
    permalink: /:name/

defaults:
  -
    scope:
      path: ""
      type: en
    values:
      layout: documentation
      lang: en

t:
  en:
    language: English
    language_title: Language
    home:
      title: Namati Documentation
      url: '/'
      description: Namati wiki.
    about:
      title: About
      url: '/about/'
